


CREATE PROCEDURE [dbo].[SI_SP_GERA_OST_CUSTO_EXTRA] AS 
/* CRIADO POR NILZA EM 03/08/2021 - SOLICITADO PELA DIRETORIA FINANCEIRA - AUTOMATIZAR A CRIAÇÃO DE MINUTAS (ORDEM DE SERVIÇO DE TRANSPORTES) PARA CONTROLE DE CUSTOS EXTRAS À PARTIR DO LANÇAMENTO DE OCORRÊNCIA LANÇADA PELA EQUIPE SAC*/

DECLARE @ID_OCH VARCHAR(MAX)
DECLARE @OBSERV VARCHAR(MAX)
DECLARE @FILCUS INT
DECLARE @CODOBS INT
DECLARE @USUINC VARCHAR(max)

DECLARE @CODFIL INT
DECLARE @SERCON VARCHAR(10)
DECLARE @CODCON INT

DECLARE @CODOST INT
DECLARE @FORMUL INT
DECLARE @ID_INF INT
DECLARE @ID_IOS INT
DECLARE @ID_COR INT

------------- INICIO DE CURSOR PARA SELECIONAR OS CONHECIMENTOS QUE POSSUEM OCORRENCIA DE ENTREGA PARA GERAÇÃO DAS MINUTAS -------------------------------------
DECLARE CURITEM CURSOR FOR 	SELECT DISTINCT 
												 RODCON.CODFIL AS FILCON, 
												 RODCON.SERCON, 
												 RODCON.CODCON,
												(SELECT DISTINCT CONVERT(VARCHAR(10),ID_OCH)  + '; ' 
														 from RODOCH H
														 where H.ID_OCH = I.ID_OCH
														 for xml path('')) AS ID_OCH ,

												 LEFT((SELECT TOP 1 H.OBSERV
														 from RODOCH H
														 where H.ID_OCH = I.ID_OCH), 30) AS OBSERV,

												(SELECT TOP 1 H.CODOBS
														 from RODOCH H
														 where H.ID_OCH = I.ID_OCH) AS CODOBS,
												 I.USUINC,
												 I.CODFIL


											FROM RODOCH I 	INNER JOIN RODNFC  ON I.ID_NFC = RODNFC.ID_NFC 
															INNER JOIN RODCON ON  RODCON.CODFIL = RODNFC.CODFIL AND RODCON.SERCON = RODNFC.SERCON AND RODCON.CODCON = RODNFC.CODCON  
															INNER JOIN RODCLI DES ON DES.CODCLIFOR = RODCON.CODDES 
															INNER JOIN RODMUN MUNDES ON DES.CODMUN = MUNDES.CODMUN  
															LEFT OUTER JOIN RODMOT ON RODCON.CODMOT = RODMOT.CODMOT  
									WHERE 
	
										RODCON.SITUAC NOT IN ('C','I') 
										AND  I.DATOCO >= DATEADD(MINUTE, -900,GETDATE())
										AND I.DATOCO <= GETDATE()
										AND I.CODOCO = 287 
										AND I.CODOBS IN (12,13,14,15,16)
										AND RODCON.CODCON <> 27265
OPEN CURITEM
	FETCH NEXT FROM CURITEM INTO  @CODFIL, @SERCON, @CODCON, @ID_OCH, @OBSERV, @CODOBS, @USUINC, @FILCUS
		WHILE (@@FETCH_STATUS<>-1) 
		BEGIN


--- ENCONTRA O PRÓXIMO NÚMERO VÁLIDO NA TABELA DE OST - RODORD --------------------------------------------------------------------------------------------
SET @CODOST = ISNULL((SELECT MAX(CODIGO) FROM RODORD WHERE CODFIL = @FILCUS AND SERORD = 'OS1'),0) + 1

--- ENCONTRA O PRÓXIMO NÚMERO DE FORMULÁRIO VÁLIDO NA TABELA DE OST - RODORD ------------------------------------------------------------------------------
SET @FORMUL = ISNULL((SELECT TOP 1 FORMUL FROM RODORD WHERE CODFIL = @FILCUS AND SERORD = 'OS1' ORDER BY DATINC DESC),0) + 1

--- ENCONTRA O PRÓXIMO ID VÁLIDO NA TABELA DE OST - RODORD -----------------------------------------------------------------------------------------------
SET @ID_COR = ISNULL((SELECT MAX(ID_COR) FROM RODCOR ),0) + 1 

----------------------------------- GERA OST ------------------------------------------------------------------------------------------------------------------
INSERT RODORD (CODIGO, SERORD, CODFIL, CODPAD,  OBSERV, TIPORD, TIPCPL, FORMUL,CODREM, CODDES, CODPAG, CODICO, CODRED, TERCOL, TERENT, CODSEG, CODLIN, CODREG, REGREM, DIFERE, PLACA, PLACA2, PLACA3, CODMOT, TIPFAT, LOCCOL, LOCENT, 
			  SITUAC, DATINC, USUINC, DATATU, USUATU,FREVAL, DESVAL, VLCOMP, COMPLE, OUTROS, TOTFRE, BASCAL, ALICOT, ICMVLR, DATCAD, TRIBUT, PERCOM, VLRADI, PERREP, VLRREP, FREPES, VLRPED, VLRCAR, VLRADM, VLRNOR, 
			  VLRESC, VLRGRI, VLRAJU, TABPAD,VLRITR, VLRCUS, DESCAR, VLRCOL, VLRENT, VLRDES, PERCUS, VLRJUR, VLRLIQ, VLRTAR,  VLREST, ID_RODIIF, OBSFIS, OBSCON, SECVAL, TIPDOC, ORDCOM)

SELECT TOP 1

			@CODOST, 'OS1', @FILCUS, CODPAD,  @ID_OCH, 
			CASE 
				WHEN @CODOBS = 12 THEN 'R'
				WHEN @CODOBS = 13 THEN 'C'
				WHEN @CODOBS = 14 THEN 'C'
				ELSE 'C' END AS TIPORD, 
	
				CASE 
				WHEN @CODOBS = 13 THEN '4'
				WHEN @CODOBS = 14 THEN '3'
				WHEN @CODOBS = 12 THEN NULL
					ELSE '3' END AS TIPCPL
	
				, @FORMUL,
				CODREM, CODDES, CODPAG, CODICO, CODRED, TERCOL, TERENT, CODSEG, CODLIN, CODREG, REGREM, 
				CASE WHEN @CODOBS = 14 THEN 'PALLETIZAÇÃO' 	ELSE NULL END AS DIFERE, PLACA, PLACA2, PLACA3, CODMOT, 'D', LOCCOL, LOCENT, 
				'D', GETDATE(), @USUINC,  GETDATE(), 'SCRIPT',--@USUINC,
				------ COMPOSICAO DE FRETE PARA GERAÇÃO DA MINUTA DE ACORDO COM O TIPO DE OCORRÊNCIA ----------------
				CASE WHEN @CODOBS <> 12 THEN 0.01 ELSE FREVAL END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE DESVAL END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLCOMP END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE COMPLE END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE OUTROS END, 
				CASE WHEN @CODOBS <> 12 THEN 0.01 ELSE TOTFRE END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE BASCAL END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE ALICOT END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE ICMVLR  END, 
				GETDATE(),  
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE TRIBUT END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE PERCOM END,
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRADI END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE PERREP END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRREP END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE FREPES END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRPED END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRCAR END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRADM END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRNOR END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRESC END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRGRI END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRAJU END, 
				TABPAD,
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRITR END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRCUS END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE DESCAR END,
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRCOL END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRENT END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRDES END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE PERCUS END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRJUR END, 
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRLIQ END,
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLRTAR END,  
				CASE WHEN @CODOBS <> 12 THEN 0 ELSE VLREST END, 
				ID_RODIIF, left(OBSFIS,100) AS OBSFIS, left(ISNULL(@OBSERV, '-') +' - '+  ISNULL(OBSCON, '-'), 240), 0, '2',
				CONVERT(VARCHAR(2), @CODFIL) +'-'+ CONVERT(VARCHAR(10), @CODCON) +'-'+ REPLACE(CONVERT(VARCHAR, GETDATE(), 102), '.', '')
FROM RODCON

WHERE RODCON.CODFIL = @CODFIL AND
	  RODCON.SERCON = @SERCON AND
	  RODCON.CODCON = @CODCON AND
	 (SELECT TOP 1 ORDCOM FROM RODORD WHERE ORDCOM = CONVERT(VARCHAR(2), @CODFIL) +'-'+ CONVERT(VARCHAR(10), @CODCON) +'-'+ REPLACE(CONVERT(VARCHAR, GETDATE(), 102), '.', '')) IS NULL 


----- GERA BINOCULO CTRC DA RODORD -----------------------------------------------------------------------------------------------------------------------------------

		INSERT RODCOR ( CODORD, SERORD, FILORD,  CODCON, SERCON, FILCON, SITUAC, TEMP, USUATU, NOMEPC, DATATU, DATINC)
		SELECT  TOP 1        @CODOST, 'OS1', @FILCUS, @CODCON, @SERCON, @CODFIL, 'D', 'N', 'SCRIPT', 'TS2', GETDATE(), GETDATE()
		FROM RODORD
		WHERE CODFIL = @FILCUS AND CODIGO = @CODOST  AND RODORD.SERORD = 'OS1'

-----GERA ITENS DA OST - ROSDIOS ------------------------------------------------------------------------------------------------------------------------------------

IF EXISTS(SELECT TOP 1 CODIGO FROM RODORD WHERE CODIGO = @CODOST AND CODFIL = @FILCUS AND SERORD = 'OS1')
EXEC SI_SP_GERA_OSTITENS_CUSTO_EXTRA @CODFIL , @CODCON , @FILCUS, @CODOST
	

FETCH NEXT FROM CURITEM INTO  @CODFIL, @SERCON, @CODCON, @ID_OCH, @OBSERV, @CODOBS, @USUINC, @FILCUS
					END
					--END
					DEALLOCATE CURITEM	
GO


