

ALTER PROCEDURE [dbo].[SI_SP_GERA_OSTITENS_CUSTO_EXTRA] (@CODFIL INT, @CODCON INT, @FILCUS INT, @CODOST INT)AS
/* CRIADO POR NILZA EM 03/08/2021 - SOLICITADO PELA DIRETORIA FINANCEIRA - AUTOMATIZAR A CRIAÇÃO DE MINUTAS (ORDEM DE SERVIÇO DE TRANSPORTES) PARA CONTROLE DE CUSTOS EXTRAS À PARTIR DO LANÇAMENTO DE OCORRÊNCIA LANÇADA PELA EQUIPE SAC
	PROCEDURE USADA PELA SI_SP_GERA_OST_CUSTO_EXTRA
*/



DECLARE @ID_INF INT
DECLARE @ID_IOS INT


BEGIN	

---------------- INICIO DO CURSOR PARA LOCALIZAR AS NOTAS DO CONHECIMENTO -------------------------------------------------------------
DECLARE CURITEM2 CURSOR FOR SELECT DISTINCT R.ID_NFC
									FROM RODNFC R
											WHERE R.CODCON = @CODCON AND R.SERCON = '2' AND R.CODFIL = @CODFIL
								

OPEN CURITEM2
	FETCH NEXT FROM CURITEM2 INTO  @ID_INF
		WHILE (@@FETCH_STATUS<>-1) 
		BEGIN

--- ENCONTRA O PRÓXIMO NÚMERO VÁLIDO NA TABELA DE COMPOSIÇÃO DE CARGA DA OST - RODORD ----------------------------------------------------
SET @ID_IOS = ISNULL((SELECT MAX(ID_IOS) FROM RODIOS WHERE  SERORD = 'OS1'),0) + 1

---------------- INSERT DAS NOTAS DO CONHECIMENTO PARA RODORD ----------------------------------------------------------------------------
	INSERT RODIOS (ID_IOS,  CODORD,  SERORD, FILORD, CODPROTR, ESPECI, QUANTI, EMPMAX, OBSERV, NATURE, VMERSE, VLRMER, PESOKG, PESCAL, PESCUB, LARGUR, ALTURA, PROFUN, CUBAGE, SERIEN, NOTFIS, DATNOT, ORDCOM, ITECOM, SITUAC, DATATU, USUATU, DATINC, CODFIS, DATENT, NUMAWB, NUHAWB,  NOTNFE, CUBGER )
				SELECT @ID_IOS + 1, @CODOST, 'OS1', @FILCUS, 1, ESPECI,        QUANTI, NULL, NULL,     NATURE, VMERSE, VLRMER, PESOKG, PESCAL, PESCUB, LARGUR, ALTURA, PROFUN, CUBAGE, SERIEN, NOTFIS, DATNOT, ORDCOM, ITECOM, SITUAC, GETDATE(), 'SCRIPT', GETDATE(), CODFIS, DATENT, NUMAWB, NUHAWB,  NOTNFE, CUBGER 
			FROM RODNFC 
			WHERE CODFIL = @CODFIL AND
					SERCON = '2' AND
					CODCON = @CODCON AND
					ID_NFC = @ID_INF AND
					 (SELECT CODIGO FROM RODORD WHERE CODIGO = @CODOST AND CODFIL = @FILCUS ) = @CODOST



FETCH NEXT FROM CURITEM2 INTO  @ID_INF
	END

	DEALLOCATE CURITEM2

END	

GO


